FoodOrderingSystem/Models/ViewModel/SubMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineFoodOrderingSystem.Models.ViewModel
{
    public class SubMenuViewModel
    {
        public int SubMenuId { get; set; }
        [Required]
        public string SubMenuName { get; set; }
    }
}

FoodOrderingSystem/Controllers/SubMenuController.cs
using FoodOrderingSystem.Models;
using OnlineFoodOrderingSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodOrderingSystem.Controllers
{
    public class SubMenuController : Controller
    {
        [Authorize(Roles = "Admin")]
        public ActionResult ManageSubMenu()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<SubMenuViewModel> lst = new List<SubMenuViewModel>();
                var empList = db.tblSubMenus.Select(x => new { SubMenuId = x.SubMenuId, SubMenuName = x.SubMenuName }).ToList();
                foreach (var item in empList)
                {
                    lst.Add(new SubMenuViewModel() { SubMenuId = item.SubMenuId, SubMenuName = item.SubMenuName });
                }
                return Json(new { data = lst }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {

                    return View(new SubMenuViewModel());
                }
            }
            else
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {
                    SubMenuViewModel sub = new SubMenuViewModel();
                    var menu = db.tblSubMenus.Where(x => x.SubMenuId == id).FirstOrDefault();
                    sub.SubMenuId = menu.SubMenuId;
                    sub.SubMenuName = menu.SubMenuName;
                    return View(sub);
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(SubMenuViewModel sm)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                if (sm.SubMenuId == 0)
                {
                    tblSubMenu tb = new tblSubMenu();
                    tb.SubMenuName = sm.SubMenuName;
                    db.tblSubMenus.Add(tb);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    tblSubMenu tbm = db.tblSubMenus.Where(m => m.SubMenuId == sm.SubMenuId).FirstOrDefault();
                    tbm.SubMenuName = sm.SubMenuName;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                tblSubMenu sm = db.tblSubMenus.Where(x => x.SubMenuId == id).FirstOrDefault();
                db.tblSubMenus.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FoodOrderingSystem/Views/SubMenu/AddOrEdit.cshtml
@model OnlineFoodOrderingSystem.Models.ViewModel.SubMenuViewModel

@{
    Layout = null;
}
@using (Html.BeginForm("AddOrEdit", "SubMenu", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.SubMenuId)

    <div class="form-group">
        @Html.LabelFor(model => model.SubMenuName, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.SubMenuName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.SubMenuName)
    </div>


    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-info" />
    </div>
}

FoodOrderingSystem/Views/SubMenu/ManageSubMenu.cshtml
@{
    ViewBag.Title = "ManageSubMenu";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">Sub Category</li>
    </ol>
</div><!--/.row-->
<!-- Main content -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                View Sub Category
                <ul class="pull-right">

                    <li style="list-style:none">
                        <a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","SubMenu")')"><i class="fa fa-plus"></i> Add New</a>
                    </li>

                </ul>

            </div>
            <div class="panel-body">


                <table id="employeeTable" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Menu Id</th>
                            <th>MenuName</th>


                            <th>Action</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>

    <script>
        var Popup, dataTable;
        $(document).ready(function () {

            $("#employeeTable").DataTable(
                {
                    "ajax": {
                        "url": "/SubMenu/GetData",
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "SubMenuId" },

                        { "data": "SubMenuName" },

                             {
                                 "data": "SubMenuId", "render": function (data) {
                                     return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","SubMenu")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete(" + data + ")><i class='fa fa-trash'></i> Delete</a>";
                                 },
                                 "orderable": false,
                                 "searchable": false,
                                 "width": "150px"
                             }


                        ],
                        "language": {

                            "emptyTable": "No data found, Please click on <b>Add New</b> Button"
                        },

                        "buttons": [
                            {
                                extend: 'copy',
                                className: 'copyButton',
                                text: '<i class="fa fa-clone"></i> Copy'
                            },
                            {
                                extend: 'excel',
                                text: '<i class="fa fa-file-excel-o"></i> Excel'
                            },
                            {
                                extend: 'pdf',
                                text: '<i class="fa fa-file-pdf-o"></i> Pdf'
                            },
                            {
                                extend: 'csv',
                                text: '<i class="fa fa-file-excel-o"></i> CSV'
                            },
                            {
                                extend: 'print',
                                text: '<i class="fa fa-print"></i> Print',
                                customize: function (win) {
                                    $(win.document.body)
                                        .css('font-size', '10pt')
                                        .prepend(
                                            '<img src="http://datatables.net/media/images/logo-fade.png" style="position:absolute; top:0; left:0;" />'
                                        );

                                    $(win.document.body).find('table')
                                        .addClass('compact')
                                        .css('font-size', 'inherit');
                                }
                            }

                        ]

                    });
                });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Fill Sub Menu Details',
                        height: 300,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            $('#employeeTable').DataTable().ajax.reload()

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }
                });
            }
            return false;
        }
         function Delete(id) {
            if(confirm('Are You Sure to Delete this Employee Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","SubMenu")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            $('#employeeTable').DataTable().ajax.reload()

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }



    </script>

}