FoodOrderingSystem/Controllers/AdminUserController.cs
using FoodOrderingSystem.Models;
using OnlineFoodOrderingSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodOrderingSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminUserController : Controller
    {
        // GET: AdminUser
        OnlineFoodDBEntities _db = new OnlineFoodDBEntities();
        public ActionResult ManageUser()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<UserViewModel> lstitem = new List<UserViewModel>();
                var lst = db.tblUsers.ToList();
                foreach (var item in lst)
                {
                    lstitem.Add(new UserViewModel() { UserId = item.UserId, Username = item.Username, Photo = item.Photo });
                }
                return Json(new { data = lstitem }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult AddOrEdit()
        {
            return View();
        }
        [HttpPost]

        public ActionResult AddOrEdit(UserViewModel uv)
        {
            tblUser tb = new tblUser();
            tb.Username = uv.Username;
            tb.Password = uv.Password;

            HttpPostedFileBase fup = Request.Files["Photo"];
            if (fup != null)
            {
                if (fup.FileName != "")
                {
                    tb.Photo = fup.FileName;
                    fup.SaveAs(Server.MapPath("~/images/UserImages/" + fup.FileName));
                }
            }
            _db.tblUsers.Add(tb);
            _db.SaveChanges();

            UserRole ud = new UserRole();
            ud.UserId = tb.UserId;
            ud.UserRolesId = 1;
            _db.UserRoles.Add(ud);
            _db.SaveChanges();
            ViewBag.Message = "User Created Successfully";


            return View();
        }
        [HttpPost]

        public ActionResult Delete(int id)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                tblUser sm = db.tblUsers.Where(x => x.UserId == id).FirstOrDefault();
                db.tblUsers.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FoodOrderingSystem/Views/AdminUser/AddOrEdit.cshtml
@model OnlineFoodOrderingSystem.Models.ViewModel.UserViewModel

@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script type="text/javascript">
    function showimagepreview1(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#smimg').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>
<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">Add/Edit User</li>
    </ol>
</div><!--/.row-->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                View Sub Category
                <ul class="pull-right">

                    <li style="list-style:none">
                        <a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","SubMenu")')"><i class="fa fa-plus"></i> Add New</a>
                    </li>

                </ul>

            </div>
            <div class="panel-body">


                <div class="box-body">
                    @using (Html.BeginForm("AddOrEdit", "AdminUser", FormMethod.Post, new { @enctype = "multipart/form-data", @onsubmit = "return SubmitForm(this)" }))
                    {

                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.UserId)





                            <div class="form-group">
                                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                                (Size 250*300)
                                <div class="col-md-10">

                                    @Html.TextBoxFor(model => model.Photo, new { @Type = "file", @class = "form-control", @onchange = "showimagepreview1(this)" })
                                    @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                <label class="control-label col-md-2"></label>
                                <div class="col-md-10">

                                    <input type="submit" value="Submit" class="btn btn-primary" />
                                    @Html.ActionLink("Back To List", "ManageUser", null, new { @class = "btn btn-info" })
                                    @ViewBag.Message
                                </div>
                            </div>
                        </div>


                    }



                </div>
            </div>
        </div>
    </div>
</div>

FoodOrderingSystem/Views/AdminUser/ManageUser.cshtml
@{
    ViewBag.Title = "ManageUser";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">Manage User</li>
    </ol>
</div><!--/.row-->
<!-- Main content -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                ManageUser
                <ul class="pull-right">

                    <li style="list-style:none">
                        <a class="btn btn-success" style="margin-bottom:10px" href="@Url.Action("AddOrEdit","AdminUser")"><i class="fa fa-plus"></i> Add New</a>
                    </li>

                </ul>

            </div>
            <div class="panel-body">



                <table id="employeeTable" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>UserId</th>

                            <th>Username</th>
                            <th>Photo</th>


                            <th>Action</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>






    <script>
        var Popup, dataTable, itemid;
        $(document).ready(function () {

            $("#employeeTable").DataTable(
                {
                    "ajax": {
                        "url": "/AdminUser/GetData",
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "UserId" },

                        { "data": "Username" },

                        {
                            "data": "Photo",
                            "render": function (data) {
                                return '<img src="/images/UserImages/' + data + '" height=50 width=50/>'
                            }
                        },


                             {
                                 "data": "UserId", "render": function (data) {

                                     return "<a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete(" + data + ")><i class='fa fa-trash'></i> Delete</a>";
                                 },
                                 "orderable": false,
                                 "searchable": false,
                                 "width": "150px"
                             }


                        ],
                        "language": {

                            "emptyTable": "No data found, Please click on <b>Add New</b> Button"
                        },

                        "buttons": [
                            {
                                extend: 'copy',
                                className: 'copyButton',
                                text: '<i class="fa fa-clone"></i> Copy'
                            },
                            {
                                extend: 'excel',
                                text: '<i class="fa fa-file-excel-o"></i> Excel'
                            },
                            {
                                extend: 'pdf',
                                text: '<i class="fa fa-file-pdf-o"></i> Pdf'
                            },
                            {
                                extend: 'csv',
                                text: '<i class="fa fa-file-excel-o"></i> CSV'
                            },
                            {
                                extend: 'print',
                                text: '<i class="fa fa-print"></i> Print',
                                customize: function (win) {
                                    $(win.document.body)
                                        .css('font-size', '10pt')
                                        .prepend(
                                            '<img src="http://datatables.net/media/images/logo-fade.png" style="position:absolute; top:0; left:0;" />'
                                        );

                                    $(win.document.body).find('table')
                                        .addClass('compact')
                                        .css('font-size', 'inherit');
                                }
                            }

                        ]

                    });
                });


         function Delete(id) {
            if(confirm('Are You Sure to Delete this User ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","AdminUser")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            $('#employeeTable').DataTable().ajax.reload()

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }



    </script>
}